Package.resolved
Package.swift

generate Package.swift
```
// swift-tools-version:5.1
import PackageDescription
let package = Package(
name: "Tools",
dependencies: [
.package(url: "https://github.com/spotify/XCMetrics", .exact("0.0.1"))
]
)
```
then, run `swift run -c release` causes error below.
`error: because package xcmetrics is required using a version-based requirement and it depends on unversion package swift-package-manager and root depends on XCMetrics 0.0.1, version solving failed.`
`swift-package-manager` uses `branch` as dependency. `branch` is treated as unversion.
use `0.3.0`
0.3.0 is same revision as swift-4.2-branch
- [swift-4.2-branch](https://github.com/apple/swift-package-manager/tree/swift-4.2-branch) rev. 235aacc
- [0.3.0](https://github.com/apple/swift-package-manager/tree/0.3.0) rev. 235aacc

Can't install v0.0.1 from SwiftPackageManager

---

DeploymentExamples/MultiInstances/xcmetrics-deployment.yaml
DeploymentExamples/MultiInstances/xcmetrics-jobs-deployment.yaml
DeploymentExamples/SingleInstance/xcmetrics-deployment.yaml
README.md
docker-compose-local.yml
docs/How to Deploy Backend.md
docs/Run the Backend Locally.md

Now that we have an official Docker Image, it's easier to run the backend locally using it without the need to build it yourself. 
This PR adds a new docker compose configuration to do that with one command:
`docker-compose -f docker-compose-local.yml up`
I also updated the documentation to simplify several steps by just using this image.

Edit doc with reference to official Docker image

---

Package.swift
Sources/XCMetricsPlugins/GitPlugin.swift
Tests/XCMetricsPluginsTests/GitPluginTests.swift

This PR proposes adding an `XCMetricsPlugin` to surface data from git and attach it to a build's metadata, taking an initial pass at resolving #9.  There are two things worth calling out:
- When initialized, the `GitPlugin` will require the path of the associated git directory to look for.  This is necessary because Xcode's `$SRCROOT` environment variable does not appear to be available along with some of the other environment variables used in `XCMetrics`, and because the `XCMetrics` executable will not be able to call git commands without knowing where to look.
- This PR includes only the options to retrieve the current branch and the latest commit on said branch, though it hopefully makes surfacing more data points from git (when needed) easy to do.
I went ahead and just copied in the …

Add GitPlugin to XCMetricsPlugins

---

docs/Getting Started.md

This PR adds some more descriptive docs on how to reuse plugins from `XCMetricsPlugins` and links to examples for possible future plugins.

Document plugin architecture with mention of XCMetricsPlugins

---

Sources/XCMetricsBackendLib/Builds/Controllers/BuildController.swift
Sources/XCMetricsBackendLib/Common/Models/Step.swift
Sources/XCMetricsBackendLib/Common/Models/Target.swift
Sources/XCMetricsBackendLib/Common/Repositories/Postgress/Migrations/AddBuildIdentifierIndexes.swift
Sources/XCMetricsBackendLib/Common/Repositories/Postgress/Migrations/AddStepIdentifiersIndexes.swift
Sources/XCMetricsBackendLib/Common/Repositories/Postgress/Migrations/AddTargetIdentifierIndexes.swift
Sources/XCMetricsBackendLib/Common/Utils/Date+Utils.swift
Sources/XCMetricsBackendLib/Common/Utils/File.swift
Sources/XCMetricsBackendLib/Common/Utils/String+Utils.swift
Sources/XCMetricsBackendLib/Config/configure.swift

As we collect more data, we started to have some slow queries. This PR addresses this issue:
1. Creates indexes for `build_identifier`, `target_identifier` and `step_identifier`.
2. Optimises the query that fetches the list of `Target` that belong to a build by using the full table name partition.
These changes resulted in the `v1/build/info` endpoint to return data in less than a second in our internal installation, before the changes it was taking 60 secs.
Additionally, adds an endpoint to fetch the list of `Step` that belong to a `Target`, that uses the same technique of using an index plus the full table name for the query. Before doing this change it was almost impossible to make a query to our `Step` table, because it was taken like 10 mins.

Add Indexes to table, optimise query and add new endpoint

---

Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/MetricsProcessor.swift
Sources/XCMetricsBackendLib/UploadMetrics/Model/UploadMetricsModel.swift
Sources/XCMetricsClient/Network/MetricsRequest.swift
Sources/XCMetricsClient/Network/MultipartRequestBuilder.swift

- Send the `sleepTime` from the host and use it to determine if it was suspended in the middle of a build.
- This new attribute is an Optional in the Backend to keep backwards compatibility with the previous version of the client that did not send it.

Determine if the host was suspended

---

.github/workflows/release.yaml

The client can't be built for Linux, mainly because of lack of `Mobius.swift` support for that OS

Remove Linux release build

---

Package.resolved
Package.swift

Bumps XCLogParser to a version that fixes a regression that caused some Swift errors generated by `xcodebuild` not being reported as such.

Report swift errors from xcodebuild

---

Sources/XCMetricsBackendLib/Config/configure.swift

Removes duplicated call to `AddBuildIdentifierIndexToBuildErrors`, this causes the docker image to fail to start locally

Fix broken migration

---

Examples/BasicApp/BasicApp.xcodeproj/xcshareddata/xcschemes/BasicApp.xcscheme
Package.resolved
Package.swift
Sources/XCMetricsBackendLib/Config/Configuration.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/MetricsProcessor.swift
Sources/XCMetricsBackendLib/UploadMetrics/Model/UploadMetricsModel.swift
Sources/XCMetricsClient/Log Management/LogParser.swift
Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderControllerFactory.swift
Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderLogic.swift
Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderLoopTypes.swift
Sources/XCMetricsClient/Mobius/Effect Handlers/DumpParser/JSONMetricsParserFactory.swift
Sources/XCMetricsClient/Mobius/Effect Handlers/DumpParser/SchemaTypeBuilders.swift
Sources/XCMetricsClient/Mobius/Effect Handlers/UploadMetricsEffectHandler.swift
Sources/XCMetricsClient/Network/MetricsPublisherService.swift
Sources/XCMetricsClient/Network/MetricsPublisherServiceHTTP.swift
Sources/XCMetricsClient/Network/MetricsRequest.swift
Sources/XCMetricsClient/Network/MultipartRequestBuilder.swift
Sources/XCMetricsClient/Utils/MetricsUploaderModel+Utils.swift
Sources/XCMetricsClient/XCMetrics.swift
Sources/XCMetricsCommon/UploadRequestExtraInfo.swift
Tests/XCMetricsTests/Effect Handlers/UploadMetricsEffectHandlerTests.swift
Tests/XCMetricsTests/MetricsUploaderLogicTests.swift
docs/Getting Started.md

In some cases, a log can contain thousands of Notes. For instance, if it has a lot of modules and is running SwiftLint as a PostBuild Phase's script. Inserting this data to the Database, can make it grow exponentially.
This PR adds an option: `--skipNotes false` that can be passed to the `XCMetrics` command so all those notes won't be inserted.

Add flag to skip inserting notes into the database

---

Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderControllerFactory.swift
Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderLogic.swift
Sources/XCMetricsClient/Mobius/Domain/MetricsUploaderLoopTypes.swift
Sources/XCMetricsClient/Mobius/Effect Handlers/UploadMetricsEffectHandler.swift
Sources/XCMetricsClient/Network/MetricsPublisherService.swift
Sources/XCMetricsClient/Network/MetricsPublisherServiceHTTP.swift
Sources/XCMetricsClient/Network/MultipartRequestBuilder.swift
Sources/XCMetricsClient/Utils/MetricsUploaderModel+Utils.swift
Sources/XCMetricsClient/XCMetrics.swift
Tests/XCMetricsTests/Effect Handlers/UploadMetricsEffectHandlerTests.swift
Tests/XCMetricsTests/MetricsUploaderLogicTests.swift
Tests/XCMetricsTests/XCMetricsUploaderArgumentTests.swift
docs/Getting Started.md

We are currently using AWS to host the XCMetrics backend and want to lock down the API so it can only be used for developers within our team. To close down the API somewhat we decided to use the functionality within API Gateway to provide a basic level of authentication.
For this to work we need to send additional headers with the `xcactivitylog ` upload requests. This is something that the XCMetrics client doesn't yet support. This PR adds support for two additional flags; `authorizationKey` and `authorizationValue`. The reason for allowing the key to be configurable was down to making this functionality as flexible as possible. Whilst a lot of cases you may use the standard `Authorisation` key, there are instances where you may just wish to use an API token with a custom key e.g …

Facilitate additional auth headers to be included within the metrics request

---

Sources/XCMetricsClient/XCMetrics.swift

Fixes NSURLErrorDomain error with code -1017 "cannot parse response".
URLSession does not support empty string header fields. If such header
is set by URLRequest, the task will fail during request encoding.
To fix this issue, we do not set default empty string authorization
headers.

Fix no authorization headers encoding

---

Sources/XCMetricsClient/Mobius/Effect Handlers/UploadMetricsEffectHandler.swift

Fixes a bug where `MetricsUploaderLogic` never ended because it was
waiting for `savedUploadRequests` which never came as it is triggered
only as result of `logsUploadFailed` event.
`logsUploadFailed` event is now always emitted and it is responsibility
of handler to check if there was any actual failures from the payload.

Always emit `logsUploadFailed` event

---

Sources/XCMetricsBackendLib/UploadMetrics/Jobs/ProcessMetricsJob.swift
Sources/XCMetricsBackendLib/UploadMetrics/Repository/LogFileRepository.swift

Fixes a bug reported in Slack by @dlbuckley. If the job failed, the logs were not being removed from the `tmp` directory.

Delete downloaded logs on error

---

Package.resolved
Package.swift
Sources/XCMetricsBackendLib/UploadMetrics/Controllers/UploadController.swift
Sources/XCMetricsBackendLib/UploadMetrics/Jobs/ProcessMetricsJob.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/MetricsProcessor.swift
Sources/XCMetricsBackendLib/UploadMetrics/Repository/LogFileGCSRepository.swift
Sources/XCMetricsBackendLib/UploadMetrics/Repository/LogFileRepository.swift
Sources/XCMetricsBackendLib/UploadMetrics/Repository/LogFileS3Repository.swift

1. Bump XCLogParser to latest version
2. Improved local file deletion. There was a case where successful processed logs were not being deleted.

Bump XCLogParser and improved deletion of local logs

---

.jazzy.yaml
Sources/XCMetricsBackendLib/Config/routes.swift
Sources/XCMetricsBackendLib/Statistics/Controllers/StatisticsController.swift
Sources/XCMetricsBackendLib/Statistics/Model/BuildStatusResult.swift

A very simple controller to be thought of as a starting point for exposing more statistics from the XCMetrics backend.

Create statistics controller with endpoint for build statuses

---

Sources/XCMetricsBackendLib/Config/configure.swift
Sources/XCMetricsBackendLib/Statistics/Controllers/StatisticsController.swift
Sources/XCMetricsBackendLib/Statistics/Jobs/DailyStatisticsJob.swift
Sources/XCMetricsBackendLib/Statistics/Model/DayBuildTime.swift
Sources/XCMetricsBackendLib/Statistics/Model/DayData.swift
Sources/XCMetricsBackendLib/Statistics/Repositories/Migrations/CreateDayBuildTime.swift
Sources/XCMetricsBackendLib/Statistics/Repositories/SQLStatisticsRepository.swift
Sources/XCMetricsBackendLib/Statistics/Repositories/StatisticsRepository.swift
Tests/XCMetricsBackendLibTests/StatisticsTests/DailyStatisticsJobTests.swift
Tests/XCMetricsBackendLibTests/StatisticsTests/StatisticsControllerTests.swift
Tests/XCMetricsBackendLibTests/StatisticsTests/TestDoubles/FakeStatisticsRepository.swift

- New `DayBuildTime` model that is ment to be created each day by the `DailyStatisticsJobs`
- Endpoint and repository functionality to store and retrieve time data of builds.

Daily build time statistics

---

docker-compose-local.yml
docker-compose.yml

When using postgres latest image (version 14),
the swift library can't connect to postgres.
Because of that we have to use fixed postgres image version.
Signed-off-by: Kaan Karakaya <yusufkaan142@gmail.com>

fix: Docker image version

---

Package.resolved
Package.swift
Tests/XCMetricsTests/Effect Handlers/CacheLogsEffectHandlerTests.swift
Tests/XCMetricsTests/Effect Handlers/LogsCleanUpEffectHandlerTests.swift
Tests/XCMetricsTests/Effect Handlers/LogsFinderEffectHandlerTests.swift
Tests/XCMetricsTests/Effect Handlers/LogsTaggerEffectHandlerTests.swift
Tests/XCMetricsTests/Effect Handlers/UploadMetricsEffectHandlerTests.swift
Tests/XCMetricsTests/LogManagerImplementationTests.swift
Tests/XCMetricsTests/MetricsUploaderLogicTests.swift
Tests/XCMetricsTests/TemporaryFile+Utils.swift

Swift Package Manager had a function called `await` that fails due to
the introduction of async/await in Swift.
XCMetrics uses functionality that now exists in [Swift Tools Core
Support](https://github.com/apple/swift-tools-support-core), so this
commit removes SPM from the package dependencies and adds the
aforementioned package instead.
In addition this commit fixes some API changes with regards to
`TemporaryFile` and `AbsolutePath`.
Inspired by the fix in [Xcparse](https://github.com/ChargePoint/xcparse/pull/63).

XCMetrics: Fix compilation for Xcode 13 beta 4 and above.

---

Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/MetricsProcessor.swift

The build metadata and xcode version were always set to `nil`, and the
build host was initialized with fake data.
Adding the real data was a matter of passing the data from
`metricsRequest`.
In addition, some refactoring was done to extract the build identifier
once.

XCMetricsBackendLib: Support build host, metadata and xcode version.

---

Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift
Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/MetricsProcessor.swift
Sources/XCMetricsClient/Network/MultipartRequestBuilder.swift
Sources/XCMetricsCommon/UploadRequestExtraInfo.swift

Depends on #64
Add build tag to `UploadRequestExtraInfo`.
I could have encoded the `Build` object and send it, but it would have
required extra boilerplate code and none of its other fields is used.

XCMetrics: Support build tag. 

---

XCMetricsLauncher

Previously, if the path contained whitespaces, the lanucher wouldn't run
the script at the given path.

XCMetricsLauncher: Wrap XCMetrics path parameter with quotes.

---

Sources/XCMetricsClient/Utils/AdditionalHeaderFactory.swift
Sources/XCMetricsClient/Utils/JSONArgument.swift
Sources/XCMetricsClient/XCMetrics.swift
docs/Getting Started.md

This way we can use a json to pass multiple arguments to request header. For example:
```
XCMetrics \
--name foo \
--additionalHeaderJson  '{"Api-Key":"yYKZ8uDrMsjlXWKOaPbCh6bU30EST2cq","Authorization":"bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYMlNtUWhudVh6LU52anR6VWlpNUZqM3V5VS1WR0hDeXdtUG5ocjBSQy1zIn0"}'
```

XCMetricsClient: Create additional header with a stringified json

---

Package.resolved
Package.swift

Includes a fix for parsing validate command errors: https://github.com/MobileNativeFoundation/XCLogParser/pull/157

Bump XCLogParser

---

Package.resolved
Package.swift

Updates swift-argument-parser and XCLogParser, also adds support for Swift 5.5 minimum version
- Adds support for Swift 5.5 SPM Package.swift
- Updates swift-argument-parser to 1.2.0 to support XCLogParser
Follow up to https://github.com/MobileNativeFoundation/XCLogParser/pull/177

Update XCLogParser to version 0.2.35

---

.github/workflows/release.yaml

After merging https://github.com/MobileNativeFoundation/XCLogParser/pull/177 we'll need to bump Xcode to pull in Swift 5.5+

Build with Xcode 13.2.1 for release

---

Sources/XCMetricsBackendLib/UploadMetrics/Repository/LogFileRepositoryFactory.swift
docs/How to Deploy Backend.md

I was deploying XCMetrics to AWS and wanted to use Aurora PostgreSQL Serverless, however the only version available is `10.14` which, I realised after the fact, is not supported by XCMetrics. The only place in the docs where PSQL's version is mentioned is in Kubernetes configs. I think it would be better if the version was explicitly stated in the `How to Deploy Backend.md` file. Though I am actually not sure if version 11 would suffice. 
Second commit, which I can push as a separate PR, just fixes a misspelling of a variable in a log message

Explicitly specify required PSQL versions in documentation

---

Dockerfile

Hello, 
We are using XCMetrics @ Blueground & we are transitioning to Arm64 for our production workloads. Since `swift:5.5-bionic` did not support Arm64 architecture, this was a blocker for us. 
This PR updates the base Docker image to `swift:5.6-focal` in order to be compatible with Arm64. 
Tested locally with the `docker-compose-local.yml` file! 🎉

Update Dockerfile to use Arm64 compatible Swift base image

---

.github/workflows/main.yaml

Workflow that build and pushes a docker image Docker hub from the `main` branch on every push to that branch. It's configured to generate an amd64 and an arm64 docker images.
This replaces the Autobuild docker images that has been created automatically in Docker hub. If this works, I'll create a another workflow that will do the same for each release and tag.

Add workflow action to build main branch docker images

---

Sources/XCMetricsBackendLib/Config/configure.swift

Not sure if this was an oversight, but the postgres configuration using the unix socket is inadvertently leaking the postgres db password to the logger.
This pr fixes the leak by only logging the pw length matching the else case.

fixed leaking password in postgres unix socket configuration

---

docs/How to Deploy Backend.md

I found typo in `docs/How to Deploy Backend.md`:
```diff
< aditionally
> additionally
```

fix docs typo in How to Deploy Backend.md: additionally

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Dockerfile
Package.swift

Increased minimum macOS version to 13.0 to fix issue #100

Increase minimum version to macOS 13.0

---

Package.resolved
Package.swift

With the current version of XCLogParser v0.2.35, you can get the following error when parsing logs:
Job failed with error: Error parsing the log: Unexpected className found parsing IDEActivityLogMessage IDEActivityLogActionMessage.
This PR updates XCLogParser to v0.2.37 and updates the Package.resolved file.
Issue: https://github.com/spotify/XCMetrics/issues/111

issue-111 update XCLogParser to v0.2.37
